'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArchiveBoxIcon,ArrowPathIcon,ChevronLeftIcon,ClipboardDocumentIcon,Cog6ToothIcon,CubeIcon,ExclamationTriangleIcon,HomeIcon,MagnifyingGlassIcon,QrCodeIcon,ShareIcon,TruckIcon,WrenchScrewdriverIcon} from '@heroicons/react/24/outline';
import {db} from '@/data/db'; import {demoMovements,demoParts} from '@/data/demo'; import {applyMovement,goodQuantity} from '@/domain/inventory'; import type {Movement,Part,Place} from '@/domain/types';
type View='home'|'parts'|'detail'|'warehouse'|'requests'|'history'|'settings';
const labels:Record<Place,string>={'buoni-1':'Ricambi buoni · Scomparto 1','buoni-3':'Ricambi buoni · Scomparto 3','buoni-7':'Ricambi buoni · Scomparto 7',guasti:'Ricambi guasti',vandalici:'Atti vandalici',a001:'A001',viaggio:'In viaggio',richiesto:'Richiesto',centrale:'Magazzino centrale'};
export function WarehouseApp(){
 const [parts,setParts]=useState<Part[]>(demoParts),[moves,setMoves]=useState<Movement[]>(demoMovements),[view,setView]=useState<View>('home'),[selected,setSelected]=useState('93000114900'),[query,setQuery]=useState(''),[online,setOnline]=useState(true),[syncing,setSyncing]=useState(false),[moveOpen,setMoveOpen]=useState(false);
 useEffect(()=>{navigator.serviceWorker?.register('/sw.js');const boot=async()=>{if(await db.parts.count()===0){await db.parts.bulkPut(demoParts);await db.movements.bulkPut(demoMovements)}setParts(await db.parts.toArray());setMoves(await db.movements.orderBy('createdAt').reverse().toArray())};void boot();const status=()=>setOnline(navigator.onLine);addEventListener('online',status);addEventListener('offline',status);return()=>{removeEventListener('online',status);removeEventListener('offline',status)}},[]);
 const pending=moves.filter(m=>m.sync==='pending').length; const current=parts.find(p=>p.code===selected)??parts[0];
 const sync=async()=>{if(!online)return;setSyncing(true);try{const ops=moves.filter(m=>m.sync==='pending');const r=await fetch('/api/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operations:ops})});if(!r.ok)throw Error();const ids:string[]=(await r.json()).accepted;await db.movements.where('id').anyOf(ids).modify({sync:'synced'});const next=await db.movements.orderBy('createdAt').reverse().toArray();setMoves(next)}finally{setSyncing(false)}};
 const navigate=(v:View)=>{setView(v);scrollTo(0,0)}; const filtered=useMemo(()=>parts.filter(p=>(p.code+' '+p.name+' '+p.description).toLowerCase().includes(query.toLowerCase())),[parts,query]);
 const saveMove=async(from:Place,to:Place,quantity:number,note:string)=>{const movement:Movement={id:crypto.randomUUID(),code:current.code,quantity,from,to,operator:'MR',note:note||undefined,createdAt:new Date().toISOString(),sync:'pending'};const updated=applyMovement(current,movement);await db.transaction('rw',db.parts,db.movements,async()=>{await db.parts.put(updated);await db.movements.put(movement)});setParts(x=>x.map(p=>p.code===updated.code?updated:p));setMoves(x=>[movement,...x]);setMoveOpen(false)};
 return <div className="app"><header><button className="brand" onClick={()=>navigate('home')}><span className="brandmark"><CubeIcon/></span><span><b>Magazzino</b><small>Ricambi tecnici</small></span></button><button className={'sync '+(!online?'offline':pending?'pending':'')} onClick={sync}><span/>{!online?'Offline':syncing?'Aggiornamento…':pending?`${pending} da inviare`:'Aggiornato'} <ArrowPathIcon/></button></header>
 <main>{view==='home'&&<Home parts={parts} navigate={navigate} setQuery={setQuery}/>} {view==='parts'&&<Parts parts={filtered} query={query} setQuery={setQuery} open={code=>{setSelected(code);navigate('detail')}}/>} {view==='detail'&&current&&<Detail part={current} moves={moves.filter(m=>m.code===current.code)} back={()=>navigate('parts')} move={()=>setMoveOpen(true)}/>} {view==='warehouse'&&<Warehouse parts={parts}/>} {view==='requests'&&<Requests parts={parts}/>} {view==='history'&&<History moves={moves}/>} {view==='settings'&&<Settings parts={parts} moves={moves}/>}</main>
 <nav aria-label="Navigazione principale"><Nav icon={HomeIcon} label="Home" active={view==='home'} onClick={()=>navigate('home')}/><Nav icon={MagnifyingGlassIcon} label="Ricambi" active={view==='parts'||view==='detail'} onClick={()=>navigate('parts')}/><button className="scan" aria-label="Scansiona QR" onClick={()=>{setQuery('93000114900');navigate('parts')}}><QrCodeIcon/></button><Nav icon={ArchiveBoxIcon} label="Magazzino" active={view==='warehouse'} onClick={()=>navigate('warehouse')}/><Nav icon={Cog6ToothIcon} label="Altro" active={view==='settings'} onClick={()=>navigate('settings')}/></nav>
 {moveOpen&&<MoveSheet part={current} close={()=>setMoveOpen(false)} save={saveMove}/>}</div>
}
function Home({parts,navigate,setQuery}:{parts:Part[];navigate:(v:View)=>void;setQuery:(v:string)=>void}){const low=parts.filter(p=>goodQuantity(p)<p.minimum).length;const today=new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'long',year:'numeric'}).format(new Date()).toLocaleUpperCase('it-IT');return <><section className="hello"><span>{today}</span><h1>Buongiorno, MR</h1><p>Cosa devi fare oggi?</p></section><div className="searchbox"><MagnifyingGlassIcon/><input aria-label="Cerca ricambio" placeholder="Cerca codice o descrizione" onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&navigate('parts')}/><button onClick={()=>navigate('parts')}><QrCodeIcon/></button></div>{low>0&&<button className="alert" onClick={()=>navigate('parts')}><ExclamationTriangleIcon/><span><b>{low} ricambi sotto scorta</b><small>Controlla le disponibilità</small></span><b>›</b></button>}<section><div className="section-title"><h2>Azioni rapide</h2></div><div className="actions"><Action icon={ArchiveBoxIcon} title="Il mio magazzino" sub="Scomparti e locazioni" color="blue" onClick={()=>navigate('warehouse')}/><Action icon={MagnifyingGlassIcon} title="Cerca ricambi" sub={`${parts.length} articoli`} color="coral" onClick={()=>navigate('parts')}/><Action icon={TruckIcon} title="Richieste" sub="In arrivo e richiesti" color="yellow" onClick={()=>navigate('requests')}/><Action icon={WrenchScrewdriverIcon} title="Storico" sub="Ultimi movimenti" color="green" onClick={()=>navigate('history')}/></div></section><section><div className="section-title"><h2>Preferiti</h2><button onClick={()=>navigate('parts')}>Vedi tutti</button></div>{parts.filter(p=>p.favorite).map(p=><button className="partrow" key={p.code} onClick={()=>{setQuery(p.code);navigate('parts')}}><span className="particon"><CubeIcon/></span><span><b>{p.name}</b><small>{p.code}</small></span><strong>{goodQuantity(p)}<small> disponibili</small></strong></button>)}</section></>}
function Parts({parts,query,setQuery,open}:{parts:Part[];query:string;setQuery:(s:string)=>void;open:(s:string)=>void}){return <><Title title="Ricambi" subtitle="Ricerca locale, anche offline"/><div className="searchbox sticky"><MagnifyingGlassIcon/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Codice, nome o descrizione"/><button><QrCodeIcon/></button></div><p className="count">{parts.length} {parts.length===1?'risultato':'risultati'}</p>{parts.length?parts.map(p=><button className="partrow" key={p.code} onClick={()=>open(p.code)}><span className="particon"><CubeIcon/></span><span><b>{p.name}</b><small>{p.code} · Min. {p.minimum}</small></span><strong className={goodQuantity(p)<p.minimum?'danger':''}>{goodQuantity(p)}<small> buoni</small></strong></button>):<div className="empty"><MagnifyingGlassIcon/><h2>Ricambio non trovato</h2><p>Controlla il codice oppure prova una descrizione diversa.</p></div>}</>}
function Detail({part,moves,back,move}:{part:Part;moves:Movement[];back:()=>void;move:()=>void}){const good=goodQuantity(part);const share=()=>navigator.share?.({title:part.name,text:`${part.name}\n${part.code}`,url:location.href});return <><button className="back" onClick={back}><ChevronLeftIcon/> Tutti i ricambi</button><section className="parthead"><span className="eyebrow">RICAMBIO</span><h1>{part.name}</h1><button className="code" onClick={()=>navigator.clipboard.writeText(part.code)}>{part.code}<ClipboardDocumentIcon/></button><p>{part.description}</p><div className="heroqty"><span><strong>{good}</strong><small>disponibili</small></span><span><b>Minimo {part.minimum}</b><small>{good<part.minimum?'Scorta bassa':'Scorta adeguata'}</small></span></div></section><section><div className="section-title"><h2>Dove si trova</h2></div><div className="locations">{Object.entries(part.stock).filter(([,q])=>q).map(([place,q])=><div key={place}><span className={'dot '+place}/><span><b>{labels[place as Place]}</b>{part.notes?.filter(n=>n.place===place).map((n,i)=><small key={i}>{n.quantity} · {n.text}</small>)}</span><strong>{q}</strong></div>)}</div></section><div className="secondary"><button onClick={()=>navigator.clipboard.writeText(part.code)}><ClipboardDocumentIcon/>Copia codice</button><button onClick={share}><ShareIcon/>Condividi</button></div><section><div className="section-title"><h2>Ultimi movimenti</h2></div>{moves.slice(0,3).map(m=><MovementRow key={m.id} m={m}/>)}</section><button className="primary floating" onClick={move}>Movimenta</button></>}
function MoveSheet({part,close,save}:{part:Part;close:()=>void;save:(f:Place,t:Place,q:number,n:string)=>void}){const available=(Object.entries(part.stock).find(([,q])=>(q??0)>0)?.[0]??'buoni-3') as Place;const [from,setFrom]=useState<Place>(available),[to,setTo]=useState<Place>('guasti'),[q,setQ]=useState(1),[note,setNote]=useState('');return <div className="scrim" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="sheet"><i/><h2>Movimenta ricambio</h2><p><b>{part.code}</b> · {part.name}</p><label>Origine<select value={from} onChange={e=>setFrom(e.target.value as Place)}>{Object.entries(part.stock).filter(([,n])=>(n??0)>0).map(([p,n])=><option key={p} value={p}>{labels[p as Place]} ({n})</option>)}</select></label><label>Destinazione<select value={to} onChange={e=>setTo(e.target.value as Place)}>{Object.entries(labels).filter(([p])=>p!==from&&p!=='richiesto').map(([p,l])=><option key={p} value={p}>{l}</option>)}</select></label><label>Quantità<input type="number" min="1" max={part.stock[from]??1} value={q} onChange={e=>setQ(Number(e.target.value))}/></label><label>Nota (facoltativa)<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Aggiungi un dettaglio utile"/></label><div className="confirm">Stai spostando <b>{q} × {part.code}</b><small>da {labels[from]} a {labels[to]}</small></div><div className="sheetactions"><button onClick={close}>Annulla</button><button className="primary" disabled={from===to||q<1||q>(part.stock[from]??0)} onClick={()=>save(from,to,q,note)}>Conferma</button></div></div></div>}
function Warehouse({parts}:{parts:Part[]}){return <><Title title="Il mio magazzino" subtitle="Ricambi buoni · configurazione 3 × 3"/><div className="grid">{Array.from({length:9},(_,i)=>i+1).map(i=>{const qty=parts.reduce((n,p)=>n+(p.stock[`buoni-${i}` as Place]??0),0);return <div key={i}><small>SCOMPARTO</small><strong>{i}</strong><span>{qty} {qty===1?'pezzo':'pezzi'}</span></div>})}</div><div className="locations"><div><span className="dot guasti"/><span><b>Ricambi guasti</b><small>Ubicazione separata</small></span><strong>{parts.reduce((n,p)=>n+(p.stock.guasti??0),0)}</strong></div><div><span className="dot a001"/><span><b>A001</b><small>Materiale con note</small></span><strong>{parts.reduce((n,p)=>n+(p.stock.a001??0),0)}</strong></div></div></>}
function Requests({parts}:{parts:Part[]}){return <><Title title="Richieste e arrivi" subtitle="Una vista semplice del materiale atteso"/>{parts.filter(p=>(p.stock.richiesto??0)+(p.stock.viaggio??0)>0).map(p=><div className="partrow" key={p.code}><span className="particon"><TruckIcon/></span><span><b>{p.name}</b><small>{p.code}</small></span><strong>{p.stock.richiesto??0}<small> richiesti</small><em>{p.stock.viaggio??0} in viaggio</em></strong></div>)}</>}
function History({moves}:{moves:Movement[]}){return <><Title title="Storico" subtitle="Registro completo e non modificabile"/>{moves.map(m=><MovementRow key={m.id} m={m}/>)}</>}
function Settings({parts,moves}:{parts:Part[];moves:Movement[]}){const exportData=async()=>{const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(parts.map(({stock,...p})=>p)),'Articoli');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(parts.flatMap(p=>Object.entries(p.stock).map(([locazione,quantita])=>({codice:p.code,locazione,quantita})))),'Giacenze');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(moves),'Movimenti');XLSX.writeFile(wb,'magazzino-tecnico.xlsx')};return <><Title title="Impostazioni" subtitle="Profilo, dati e configurazione"/><div className="settings"><button><span><b>Operatore MR</b><small>Ruolo base</small></span>›</button><button onClick={exportData}><span><b>Esporta Excel</b><small>Articoli, giacenze e movimenti</small></span>›</button><button><span><b>Rivedi tutorial</b><small>Le funzioni essenziali in 5 passi</small></span>›</button><button><span><b>Accesso Manager</b><small>Richiede PIN</small></span>›</button></div></>}
function MovementRow({m}:{m:Movement}){return <div className="movement"><span className="moveicon"><ArrowPathIcon/></span><span><b>{m.from?labels[m.from]:'Nuovo'} → {m.to?labels[m.to]:'Rettifica'}</b><small>{new Intl.DateTimeFormat('it',{dateStyle:'medium',timeStyle:'short'}).format(new Date(m.createdAt))} · {m.operator}</small>{m.note&&<em>{m.note}</em>}</span><strong>{m.quantity}</strong></div>}
function Title({title,subtitle}:{title:string;subtitle:string}){return <section className="title"><h1>{title}</h1><p>{subtitle}</p></section>};function Action({icon:Icon,title,sub,color,onClick}:{icon:typeof CubeIcon;title:string;sub:string;color:string;onClick:()=>void}){return <button className="action" onClick={onClick}><span className={color}><Icon/></span><b>{title}</b><small>{sub}</small></button>};function Nav({icon:Icon,label,active,onClick}:{icon:typeof HomeIcon;label:string;active:boolean;onClick:()=>void}){return <button className={active?'active':''} onClick={onClick}><Icon/><small>{label}</small></button>}
