import {createSign} from 'node:crypto';
import type {Bin,LocationConfig,Movement,Part,WarehouseConfig} from '@/domain/types';
import {applyMovement} from '@/domain/inventory';
import {defaultConfiguration,defaultLocations,mergeBins,mergeByKey,mergeLww,mergeParts} from '@/sync/catalog';
import {hasProtectedCatalogChanges,ManagerAuthorizationError,mergeProtectedParts} from '@/server/catalogAuthorization';
import type {RemoteStore} from './types';

type RequestState={code:string;requested:number;travelling:number;updatedAt?:string;updatedBy?:string};
export const SHEET_HEADERS={ARTICOLI:['code','updatedAt','updatedBy','json'],LOCAZIONI:['id','updatedAt','updatedBy','json'],SCOMPARTI:['id','updatedAt','updatedBy','json'],MOVIMENTI:['id','createdAt','code','quantity','from','to','operator','note','kind','delta'],RICHIESTE:['code','updatedAt','updatedBy','json'],CONFIGURAZIONE:['id','updatedAt','updatedBy','json'],SYNC_META:['key','value','updatedAt','deviceId']} as const;
export type SheetName=keyof typeof SHEET_HEADERS;
export class GoogleSheetsError extends Error{constructor(message:string,public readonly status=500){super(message);this.name='GoogleSheetsError'}}
const b64=(value:string|Buffer)=>Buffer.from(value).toString('base64url');
let tokenCache:{value:string;expires:number}|undefined;
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

async function fetchRetry(url:string,init:RequestInit){for(let attempt=0;attempt<3;attempt++){let response:Response;try{response=await fetch(url,{...init,signal:AbortSignal.timeout(10_000)})}catch(error){if(attempt===2)throw new GoogleSheetsError('Timeout durante la connessione a Google Sheets',504);await wait(25*2**attempt);continue}if(![408,429,500,502,503,504].includes(response.status)||attempt===2)return response;await wait(25*2**attempt)}throw new GoogleSheetsError('Google Sheets non disponibile')}
async function accessToken(){if(tokenCache&&tokenCache.expires>Date.now()+60_000)return tokenCache.value;const email=process.env.GOOGLE_CLIENT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,'\n');if(!email||!key)throw new GoogleSheetsError('Credenziali Google incomplete');const now=Math.floor(Date.now()/1000),unsigned=`${b64(JSON.stringify({alg:'RS256',typ:'JWT'}))}.${b64(JSON.stringify({iss:email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}))}`,assertion=`${unsigned}.${b64(createSign('RSA-SHA256').update(unsigned).sign(key))}`;const response=await fetchRetry('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});if(!response.ok)throw new GoogleSheetsError(response.status===401?'Autenticazione Google rifiutata':`Autenticazione Google non riuscita (${response.status})`,response.status);const body=await response.json() as {access_token?:string;expires_in?:number};if(!body.access_token)throw new GoogleSheetsError('Risposta OAuth Google non valida');tokenCache={value:body.access_token,expires:Date.now()+(body.expires_in??3600)*1000};return tokenCache.value}
async function values(range:string,rows?:unknown[][]){const id=process.env.GOOGLE_SHEET_ID;if(!id)throw new GoogleSheetsError('GOOGLE_SHEET_ID mancante');const suffix=rows?':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS':'';const response=await fetchRetry(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(range)}${suffix}`,{method:rows?'POST':'GET',headers:{authorization:`Bearer ${await accessToken()}`,'content-type':'application/json'},body:rows?JSON.stringify({values:rows}):undefined});if(!response.ok){if(response.status===403)throw new GoogleSheetsError('Service Account senza accesso al foglio',403);if(response.status===404)throw new GoogleSheetsError('Google Sheet o tab non trovato',404);throw new GoogleSheetsError(`Google Sheets non disponibile (${response.status})`,response.status)}return response.json() as Promise<{values?:unknown[][]}>}
async function readJson<T>(sheet:SheetName){const data=await values(`${sheet}!A2:D`);return (data.values??[]).flatMap(row=>{if(row.every(cell=>String(cell).trim()===''))return [];try{return [JSON.parse(String(row[3])) as T]}catch{return []}})}
async function appendVersions<T extends {updatedAt?:string;updatedBy?:string}>(sheet:SheetName,key:(value:T)=>string,current:T[],incoming:T[]){const known=new Set(current.map(value=>`${key(value)}|${value.updatedAt??''}|${value.updatedBy??''}`)),fresh=incoming.filter(value=>!known.has(`${key(value)}|${value.updatedAt??''}|${value.updatedBy??''}`));if(fresh.length)await values(`${sheet}!A:D`,fresh.map(value=>[key(value),value.updatedAt??'',value.updatedBy??'',JSON.stringify(value)]))}
function decodeMovement(row:unknown[]):Movement|null{if(row.every(cell=>String(cell).trim()===''))return null;const quantity=Number(row[3]),createdAt=String(row[1]);if(!String(row[0])||!String(row[2])||!Number.isInteger(quantity)||quantity<=0||Number.isNaN(Date.parse(createdAt))||!String(row[6]))return null;return {id:String(row[0]),createdAt,code:String(row[2]),quantity,from:row[4]?String(row[4]) as Movement['from']:undefined,to:row[5]?String(row[5]) as Movement['to']:undefined,operator:String(row[6]),note:row[7]?String(row[7]):undefined,kind:row[8]?String(row[8]) as Movement['kind']:undefined,delta:row[9]===''||row[9]===undefined?undefined:Number(row[9]),sync:'synced'}}
const requestsFrom=(parts:Part[]):RequestState[]=>parts.map(part=>({code:part.code,requested:part.stock.richiesto??0,travelling:part.stock.viaggio??0,updatedAt:part.updatedAt,updatedBy:part.updatedBy}));

export class GoogleSheetsStore implements RemoteStore{
 async validateSchema(){const result={} as Record<SheetName,'ok'>;for(const sheet of Object.keys(SHEET_HEADERS) as SheetName[]){let data:{values?:unknown[][]};try{data=await values(`${sheet}!1:1`)}catch(error){if(error instanceof GoogleSheetsError&&error.status===404)throw new GoogleSheetsError(`Tab ${sheet} non trovato`,404);throw error}const actual=(data.values?.[0]??[]).map(String),expected=[...SHEET_HEADERS[sheet]];if(actual.length!==expected.length||actual.some((value,index)=>value!==expected[index]))throw new GoogleSheetsError(`Intestazioni ${sheet} non valide`,422);result[sheet]='ok'}return result}
 async diagnostics(){const sheets=await this.validateSchema();await values('ARTICOLI!A2:D2');return {googleAuth:'ok' as const,spreadsheetAccess:'ok' as const,sheets,read:'ok' as const}}
 async allMovements(){const data=await values('MOVIMENTI!A2:J');const unique=new Map<string,Movement>();for(const row of data.values??[]){const decoded=decodeMovement(row);if(decoded&&!unique.has(decoded.id))unique.set(decoded.id,decoded)}return [...unique.values()]}
 async sync({cursor,operations,catalog,deviceId}:Parameters<RemoteStore['sync']>[0],authorization:Parameters<RemoteStore['sync']>[1]={manager:false}){
  await this.validateSchema();
  const [log,partVersions,binVersions,locationVersions,requestVersions,configurationVersions]=await Promise.all([this.allMovements(),readJson<Part>('ARTICOLI'),readJson<Bin>('SCOMPARTI'),readJson<LocationConfig>('LOCAZIONI'),readJson<RequestState>('RICHIESTE'),readJson<WarehouseConfig>('CONFIGURAZIONE')]);
  const storedParts=mergeParts([],partVersions),storedBins=mergeBins([],binVersions),storedLocations=mergeByKey([],locationVersions,value=>value.id),storedRequests=mergeByKey([],requestVersions,value=>value.code),storedConfiguration=configurationVersions.reduce((value,next)=>mergeLww(value,next),defaultConfiguration),current={parts:storedParts,bins:storedBins,locations:storedLocations,configuration:storedConfiguration};
  const protectedChanges=hasProtectedCatalogChanges(current,catalog);if(protectedChanges&&!authorization.manager)throw new ManagerAuthorizationError();
  const inConflict=cursor<log.length,serverHasNewer=inConflict;
  const initial=storedParts.length===0;let parts=initial?mergeParts([],catalog.parts):protectedChanges?mergeProtectedParts(storedParts,catalog.parts):storedParts;
  if(storedRequests.length)parts=parts.map(part=>{const state=storedRequests.find(value=>value.code===part.code);return state?{...part,stock:{...part.stock,richiesto:state.requested,viaggio:state.travelling}}:part});
  const bins=protectedChanges?mergeBins(storedBins,catalog.bins):storedBins,locations=protectedChanges?mergeByKey(storedLocations,catalog.locations,value=>value.id):storedLocations,configuration=protectedChanges?mergeLww(storedConfiguration,catalog.configuration):storedConfiguration;
  const ids=new Set(log.map(value=>value.id)),fresh=operations.filter(value=>!ids.has(value.id));if(!initial)for(const operation of fresh)parts=parts.map(part=>part.code===operation.code?({...applyMovement(part,operation),updatedAt:operation.createdAt,updatedBy:operation.operator}):part);
  const requestStates=requestsFrom(parts);
  await appendVersions('ARTICOLI',value=>value.code,partVersions,parts);await appendVersions('LOCAZIONI',value=>value.id,locationVersions,locations);await appendVersions('SCOMPARTI',value=>value.id,binVersions,bins);await appendVersions('RICHIESTE',value=>value.code,requestVersions,requestStates);await appendVersions('CONFIGURAZIONE',value=>value.id,configurationVersions,[configuration]);
  // Re-read IDs immediately before append: a retry after an ambiguous timeout remains idempotent.
  const latest=await this.allMovements(),latestIds=new Set(latest.map(value=>value.id)),toAppend=fresh.filter(value=>!latestIds.has(value.id));if(toAppend.length)await values('MOVIMENTI!A:J',toAppend.map(value=>[value.id,value.createdAt,value.code,value.quantity,value.from??'',value.to??'',value.operator,value.note??'',value.kind??'move',value.delta??'']));
  const all=[...latest,...toAppend.map(value=>({...value,sync:'synced' as const}))];await values('SYNC_META!A:D',[['cursor',all.length,new Date().toISOString(),deviceId]]);
  return {accepted:operations.map(value=>value.id),changes:all.slice(cursor),cursor:all.length,serverHasNewer,catalog:{parts,bins,locations:locations.length?locations:defaultLocations,configuration}};
 }
}
export function resetGoogleTokenCache(){tokenCache=undefined}
