import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
vi.mock('node:crypto',()=>({createSign:()=>({update(){return this},sign(){return Buffer.from('signature')}})}));
import {GoogleSheetsStore,resetGoogleTokenCache,SHEET_HEADERS} from './googleSheets';

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
function googleFetch(options:{badHeader?:string;missing?:string;transient?:number}={}){let transient=options.transient??0;return vi.fn(async(input:string|URL|Request)=>{const url=String(input);if(url.includes('oauth2.googleapis.com'))return json({access_token:'test-token',expires_in:3600});if(transient-->0)return json({},429);const decoded=decodeURIComponent(url),sheet=(Object.keys(SHEET_HEADERS) as (keyof typeof SHEET_HEADERS)[]).find(name=>decoded.includes(`${name}!`));if(sheet===options.missing)return json({},404);if(decoded.includes('!1:1'))return json({values:[[...(SHEET_HEADERS[sheet!]??[]).map(value=>sheet===options.badHeader&&value==='json'?'wrong':value)]]});return json({values:[]})})}
describe('GoogleSheetsStore senza Google reale',()=>{beforeEach(()=>{process.env.GOOGLE_CLIENT_EMAIL='service@example.test';process.env.GOOGLE_PRIVATE_KEY='test-key';process.env.GOOGLE_SHEET_ID='sheet-id';resetGoogleTokenCache()});afterEach(()=>vi.unstubAllGlobals());
 it('valida OAuth, sette tab, intestazioni e lettura',async()=>{const fetch=googleFetch();vi.stubGlobal('fetch',fetch);const result=await new GoogleSheetsStore().diagnostics();expect(Object.keys(result.sheets)).toHaveLength(7);expect(result.read).toBe('ok');expect(fetch.mock.calls.filter((call:unknown[])=>String(call[0]).includes('oauth2')).length).toBe(1)});
 it('segnala tab mancante e intestazione errata',async()=>{vi.stubGlobal('fetch',googleFetch({missing:'MOVIMENTI'}));await expect(new GoogleSheetsStore().validateSchema()).rejects.toThrow('Tab MOVIMENTI non trovato');resetGoogleTokenCache();vi.stubGlobal('fetch',googleFetch({badHeader:'ARTICOLI'}));await expect(new GoogleSheetsStore().validateSchema()).rejects.toThrow('Intestazioni ARTICOLI non valide')});
 it('ritenta una risposta temporanea 429 e poi riesce',async()=>{const fetch=googleFetch({transient:1});vi.stubGlobal('fetch',fetch);await expect(new GoogleSheetsStore().validateSchema()).resolves.toBeDefined();expect(fetch).toHaveBeenCalled()});
 it('traduce accesso negato senza esporre la risposta Google',async()=>{vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request)=>String(input).includes('oauth2')?json({access_token:'token'}):json({internal:'secret'},403)));await expect(new GoogleSheetsStore().validateSchema()).rejects.toThrow('Service Account senza accesso')});
});
