import {createSign} from 'node:crypto';
import type {Movement} from '@/domain/types';
import type {RemoteStore} from './types';
const b64=(value:string|Buffer)=>Buffer.from(value).toString('base64url');
async function token(){const email=process.env.GOOGLE_CLIENT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,'\n');if(!email||!key)throw new Error('Credenziali Google incomplete');const now=Math.floor(Date.now()/1000),unsigned=`${b64(JSON.stringify({alg:'RS256',typ:'JWT'}))}.${b64(JSON.stringify({iss:email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}))}`,assertion=`${unsigned}.${b64(createSign('RSA-SHA256').update(unsigned).sign(key))}`;const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});if(!response.ok)throw new Error(`OAuth Google: ${response.status}`);return (await response.json() as {access_token:string}).access_token}
async function values(range:string,init?:RequestInit){const id=process.env.GOOGLE_SHEET_ID;if(!id)throw new Error('GOOGLE_SHEET_ID mancante');const response=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(range)}${init?':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS':''}`,{...init,headers:{authorization:`Bearer ${await token()}`,'content-type':'application/json'}});if(!response.ok)throw new Error(`Google Sheets: ${response.status} ${await response.text()}`);return response.json() as Promise<{values?:unknown[][]}>}
const decode=(row:unknown[]):Movement=>({id:String(row[0]),createdAt:String(row[1]),code:String(row[2]),quantity:Number(row[3]),from:row[4]?String(row[4]) as Movement['from']:undefined,to:row[5]?String(row[5]) as Movement['to']:undefined,operator:String(row[6]),note:row[7]?String(row[7]):undefined,kind:row[8]?String(row[8]) as Movement['kind']:undefined,delta:row[9]===''?undefined:Number(row[9]),sync:'synced'});
export class GoogleSheetsStore implements RemoteStore{
 async allMovements(){const data=await values('MOVIMENTI!A2:J');return (data.values??[]).map(decode)}
 async sync({cursor,operations}:Parameters<RemoteStore['sync']>[0]){const current=await this.allMovements(),ids=new Set(current.map(m=>m.id)),fresh=operations.filter(m=>!ids.has(m.id));if(fresh.length)await values('MOVIMENTI!A:J',{method:'POST',body:JSON.stringify({values:fresh.map(m=>[m.id,m.createdAt,m.code,m.quantity,m.from??'',m.to??'',m.operator,m.note??'',m.kind??'move',m.delta??''])})});const all=[...current,...fresh.map(m=>({...m,sync:'synced' as const}))];return {accepted:operations.map(m=>m.id),changes:all.slice(cursor),cursor:all.length,serverHasNewer:cursor<current.length}}
}
